name: Nightly Test Job Against Latest Mypy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      FORCE_COLOR: 1
      TERM: xterm-color
      PYTEST_ADDOPTS: --color=yes

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Pip install
        run: |
          make install
          pip install -U git+https://github.com/python/mypy.git

      - name: Run unit tests
        run: make test

      - name: Run e2e tests
        run: make test-e2e
